services:
  miningbots-manager:
    image: miningbots-coolify-manager
    build: .
    init: true
    container_name: miningbots-manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/mcm-data:/tmp
    labels:
      - "traefik.http.middlewares.login-auth.basicauth.users=${PASSWORD_HASH:?}"
      - "traefik.http.routers.https-0-${COOLIFY_RESOURCE_UUID:?}.middlewares=login-auth"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - fe_host=${fe_host:?}
      - BASE_DOMAIN=${BASE_DOMAIN:?}
