services:
  miningbots-manager:
    image: miningbots-coolify-manager
    build: .
    container_name: miningbots-manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.http.middlewares.login-auth.basicauth.users=${PASSWORD_HASH}"
      - "traefik.http.routers.https-0-${serviceID}.middlewares=login-auth"
