#!/usr/local/bin/python3

from sqlalchemy import create_engine, text
from sqlalchemy.orm import declarative_base
import os, sys, getpass, argon2
import secrets
engine=create_engine(os.environ['POSTGRES_CONNECT_URI'])

Base = declarative_base()
class IMUserEntry(Base):
    from sqlalchemy import Column, String
    __tablename__ = "im_users"

    id = Column(String, primary_key=True)
    password = Column(String, nullable=False) # not the password, the hex hash
Base.metadata.create_all(engine)

with engine.connect() as conn:
    conn.begin()
    if conn.execute(text("SELECT id FROM im_users WHERE id=:id"),{"id":sys.argv[1]}).fetchone() is None:
            print("User does not exist")
            sys.exit(1)
    conn.execute(text("UPDATE im_users SET password=:password, \"passwordChangeNonce\"=:nonce WHERE id=:id"),{"id":sys.argv[1],"password":argon2.PasswordHasher().hash(getpass.getpass("Password: ")),"nonce":secrets.randbits(63)})
    conn.commit()
